<?php

/**
 * BaseBooking
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $apartment_id
 * @property integer $client_id
 * @property date $date_from
 * @property date $date_to
 * @property integer $pax
 * @property float $price
 * @property boolean $valid
 * @property boolean $canceled
 * @property Apartment $Apartment
 * @property sfGuardUser $Client
 * 
 * @method integer     getApartmentId()  Returns the current record's "apartment_id" value
 * @method integer     getClientId()     Returns the current record's "client_id" value
 * @method date        getDateFrom()     Returns the current record's "date_from" value
 * @method date        getDateTo()       Returns the current record's "date_to" value
 * @method integer     getPax()          Returns the current record's "pax" value
 * @method float       getPrice()        Returns the current record's "price" value
 * @method boolean     getValid()        Returns the current record's "valid" value
 * @method boolean     getCanceled()     Returns the current record's "canceled" value
 * @method Apartment   getApartment()    Returns the current record's "Apartment" value
 * @method sfGuardUser getClient()       Returns the current record's "Client" value
 * @method Booking     setApartmentId()  Sets the current record's "apartment_id" value
 * @method Booking     setClientId()     Sets the current record's "client_id" value
 * @method Booking     setDateFrom()     Sets the current record's "date_from" value
 * @method Booking     setDateTo()       Sets the current record's "date_to" value
 * @method Booking     setPax()          Sets the current record's "pax" value
 * @method Booking     setPrice()        Sets the current record's "price" value
 * @method Booking     setValid()        Sets the current record's "valid" value
 * @method Booking     setCanceled()     Sets the current record's "canceled" value
 * @method Booking     setApartment()    Sets the current record's "Apartment" value
 * @method Booking     setClient()       Sets the current record's "Client" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBooking extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('booking');
        $this->hasColumn('apartment_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('client_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('date_from', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('date_to', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('pax', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('price', 'float', null, array(
             'type' => 'float',
             'notnull' => true,
             ));
        $this->hasColumn('valid', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
        $this->hasColumn('canceled', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Apartment', array(
             'local' => 'apartment_id',
             'foreign' => 'id'));

        $this->hasOne('sfGuardUser as Client', array(
             'local' => 'client_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}