<?php

/**
 * BasePicture
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $apartment_id
 * @property string $path
 * @property string $type
 * @property string $name
 * @property string $description
 * @property Apartment $Apartment
 * 
 * @method integer   getApartmentId()  Returns the current record's "apartment_id" value
 * @method string    getPath()         Returns the current record's "path" value
 * @method string    getType()         Returns the current record's "type" value
 * @method string    getName()         Returns the current record's "name" value
 * @method string    getDescription()  Returns the current record's "description" value
 * @method Apartment getApartment()    Returns the current record's "Apartment" value
 * @method Picture   setApartmentId()  Sets the current record's "apartment_id" value
 * @method Picture   setPath()         Sets the current record's "path" value
 * @method Picture   setType()         Sets the current record's "type" value
 * @method Picture   setName()         Sets the current record's "name" value
 * @method Picture   setDescription()  Sets the current record's "description" value
 * @method Picture   setApartment()    Sets the current record's "Apartment" value
 * 
 * @package    Adriatic.hr tecaj projekt
 * @subpackage model
 * @author     Tino
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePicture extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('picture');
        $this->hasColumn('apartment_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('path', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('type', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Apartment', array(
             'local' => 'apartment_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}