<?php

/**
 * BaseApartmentFeature
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $apartment_id
 * @property integer $feature_id
 * @property Apartment $Apartment
 * @property Feature $Feature
 * 
 * @method integer          getApartmentId()  Returns the current record's "apartment_id" value
 * @method integer          getFeatureId()    Returns the current record's "feature_id" value
 * @method Apartment        getApartment()    Returns the current record's "Apartment" value
 * @method Feature          getFeature()      Returns the current record's "Feature" value
 * @method ApartmentFeature setApartmentId()  Sets the current record's "apartment_id" value
 * @method ApartmentFeature setFeatureId()    Sets the current record's "feature_id" value
 * @method ApartmentFeature setApartment()    Sets the current record's "Apartment" value
 * @method ApartmentFeature setFeature()      Sets the current record's "Feature" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseApartmentFeature extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('apartment_feature');
        $this->hasColumn('apartment_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('feature_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Apartment', array(
             'local' => 'apartment_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Feature', array(
             'local' => 'feature_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}