<?php

/**
 * BaseFeature
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $description
 * @property string $icon_path
 * @property Doctrine_Collection $Features
 * @property Doctrine_Collection $ApartmentFeature
 * 
 * @method string              getName()             Returns the current record's "name" value
 * @method string              getDescription()      Returns the current record's "description" value
 * @method string              getIconPath()         Returns the current record's "icon_path" value
 * @method Doctrine_Collection getFeatures()         Returns the current record's "Features" collection
 * @method Doctrine_Collection getApartmentFeature() Returns the current record's "ApartmentFeature" collection
 * @method Feature             setName()             Sets the current record's "name" value
 * @method Feature             setDescription()      Sets the current record's "description" value
 * @method Feature             setIconPath()         Sets the current record's "icon_path" value
 * @method Feature             setFeatures()         Sets the current record's "Features" collection
 * @method Feature             setApartmentFeature() Sets the current record's "ApartmentFeature" collection
 * 
 * @package    Adriatic.hr tecaj projekt
 * @subpackage model
 * @author     Tino
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFeature extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('feature');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('icon_path', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Apartment as Features', array(
             'refClass' => 'ApartmentFeature',
             'local' => 'feature_id',
             'foreign' => 'apartment_id'));

        $this->hasMany('ApartmentFeature', array(
             'local' => 'id',
             'foreign' => 'feature_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}