<?php

/**
 * FeatureTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FeatureTable extends Doctrine_Table {


	public function GetByIds( $ids=array() ) {

		if (count($ids) > 0) {
		
			$q = $this->createQuery('f')
				   ->whereIn('f.id', $ids);
			return  $q->execute();

		     } else {
			return false;
		}
		
	}


	/**
	 * Returns an instance of this class.
	 *
	 * @return object FeatureTable
	 */
	public static function getInstance()
	{
		return Doctrine_Core::getTable('Feature');
	}
}