# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/04-Settings

prod:
  .settings:
    no_script_name:         true
    logging_enabled:         false

dev:
  .settings:
    error_reporting:          <?php echo (E_ALL | E_STRICT)."\n" ?>
    web_debug:               true
    cache:                       false
    no_script_name:        false
    etag:                         false

test:
  .settings:
    error_reporting:         <?php echo ((E_ALL | E_STRICT) ^ E_NOTICE)."\n" ?>
    cache:                       false
    web_debug:               false
    no_script_name:        false
    etag:                         false
all:
  .settings:

    # Language
    i18n: true
    default_culture: en_EN
    charset: utf-8

    # Helpers 
    standard_helpers: [Partial, Cache, I18N]

    # HTTP 1.1 ETag enabled
    etag:                         true

    # Form security secret (CSRF protection)
    csrf_secret:               de93197d0d221bf6a093cd9d0b695d9c37db5e65

    # Output escaping settings
    escaping_strategy:    true
    escaping_method:     ESC_SPECIALCHARS

    # Enable the database manager
    use_database:           true

    #Sf Guard plugin
    enabled_modules:     [default, sfGuardAuth]

    login_module:           sfGuardAuth
    login_action:             signin

    secure_module:        sfGuardAuth
    secure_action:          secure