<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addapartmentfeature extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('apartment_feature', array(
             'apartment_id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'length' => 8,
             ),
             'feature_id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'length' => 8,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'apartment_id',
              1 => 'feature_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('apartment_feature');
    }
}