<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ExtendSfUser extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('sf_guard_user', 'location', 'string', '', array(
             ));
        $this->addColumn('sf_guard_user', 'hometown', 'string', '', array(
             ));
        $this->addColumn('sf_guard_user', 'gender', 'enum', '', array(
             'values' => 
             array(
              0 => 'male',
              1 => 'female',
             ),
             ));
        $this->addColumn('sf_guard_user', 'locale', 'string', '', array(
             ));
        $this->addColumn('sf_guard_user', 'timezone', 'string', '', array(
             ));
        $this->addColumn('sf_guard_user', 'facebook_id', 'integer', '5', array(
             'unique' => '1',
             ));
        $this->addColumn('sf_guard_user', 'facebook_verified', 'boolean', '25', array(
             ));
        $this->addColumn('sf_guard_user', 'facebook_link', 'string',  array(
             ));
        $this->addColumn('sf_guard_user', 'facebook_location_id', 'integer', '8', array(
             ));
        $this->addColumn('sf_guard_user', 'facebook_hometown_id', 'integer', '8', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('sf_guard_user', 'location');
        $this->removeColumn('sf_guard_user', 'hometown');
        $this->removeColumn('sf_guard_user', 'gender');
        $this->removeColumn('sf_guard_user', 'locale');
        $this->removeColumn('sf_guard_user', 'timezone');
        $this->removeColumn('sf_guard_user', 'facebook_id');
        $this->removeColumn('sf_guard_user', 'facebook_verified');
        $this->removeColumn('sf_guard_user', 'facebook_link');
        $this->removeColumn('sf_guard_user', 'facebook_location_id');
        $this->removeColumn('sf_guard_user', 'facebook_hometown_id');
    }
}