<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addfks extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('apartment', 'apartment_city_id_city_id', array(
             'name' => 'apartment_city_id_city_id',
             'local' => 'city_id',
             'foreign' => 'id',
             'foreignTable' => 'city',
             ));
        $this->createForeignKey('apartment_feature', 'apartment_feature_apartment_id_apartment_id', array(
             'name' => 'apartment_feature_apartment_id_apartment_id',
             'local' => 'apartment_id',
             'foreign' => 'id',
             'foreignTable' => 'apartment',
             'onUpdate' => NULL,
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('apartment_feature', 'apartment_feature_feature_id_feature_id', array(
             'name' => 'apartment_feature_feature_id_feature_id',
             'local' => 'feature_id',
             'foreign' => 'id',
             'foreignTable' => 'feature',
             'onUpdate' => NULL,
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('booking', 'booking_apartment_id_apartment_id', array(
             'name' => 'booking_apartment_id_apartment_id',
             'local' => 'apartment_id',
             'foreign' => 'id',
             'foreignTable' => 'apartment',
             ));
        $this->createForeignKey('period', 'period_apartment_id_apartment_id', array(
             'name' => 'period_apartment_id_apartment_id',
             'local' => 'apartment_id',
             'foreign' => 'id',
             'foreignTable' => 'apartment',
             ));
    }

    public function down()
    {
        $this->dropForeignKey('apartment', 'apartment_city_id_city_id');
        $this->dropForeignKey('apartment_feature', 'apartment_feature_apartment_id_apartment_id');
        $this->dropForeignKey('apartment_feature', 'apartment_feature_feature_id_feature_id');
        $this->dropForeignKey('booking', 'booking_apartment_id_apartment_id');
        $this->dropForeignKey('period', 'period_apartment_id_apartment_id');
    }
}