<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ExtendBooking extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('booking', 'valid', 'boolean', '25', array(
             'default' => '0',
             ));
        $this->addColumn('booking', 'canceled', 'boolean', '25', array(
             'default' => '0',
             ));
    }

    public function down()
    {
    }
}