<?php

/**
 * ApartmentFeatureTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ApartmentFeatureTable extends Doctrine_Table{



    /**
     * Returns an instance of this class.
     *
     * @return object ApartmentFeatureTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ApartmentFeature');
    }


    
}