<?php

/**
 * CityTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CityTable extends Doctrine_Table {

	public static function getInstance() {
		return Doctrine_Core::getTable('City');
	}

	public function FindByNameLike($name) {
	      
		 $q = $this->createQuery('c')
			->where('name LIKE ?', $name);

		 return $q->fetchOne();
	}


	public function TopCities($limit = 4) {

		$q = $this->createQuery('c')
			->select('c.id, c.name, count(a.id) as count')
		        	->limit($limit)
		        	->leftJoin('c.Apartments a')
		        	->groupBy('c.id')
		        	->orderBy('count DESC');

		 return $q -> execute();
	}




}